//! AsyncAPI 2.6 document generator.
//!
//! Each declared namespace becomes one channel under
//! `channels."{namespace}.{*}"` with `publish` and `subscribe`
//! operations carrying the supplied JSON Schema as the payload.

use anyhow::Result;
use serde_json::{Value, json};

/// Render an AsyncAPI 2.6 document covering `namespaces`.
///
/// # Errors
///
/// Returns an error only if `serde_yaml` fails to serialize the
/// generated structure (which is unreachable for valid input).
pub fn render(namespaces: &[(String, Value)]) -> Result<String> {
    let mut channels = serde_json::Map::new();
    let mut schemas = serde_json::Map::new();

    for (name, schema) in namespaces {
        let component_ref = format!("#/components/schemas/{name}Payload");
        schemas.insert(format!("{name}Payload"), schema.clone());
        let channel_path = format!("{name}.{{channelTail}}");
        channels.insert(
            channel_path.clone(),
            json!({
                "parameters": {
                    "channelTail": {
                        "description": "Channel suffix after the namespace separator",
                        "schema": { "type": "string" },
                    }
                },
                "publish": {
                    "operationId": format!("publish_{name}"),
                    "message": {
                        "name": format!("{name}Publication"),
                        "payload": { "$ref": component_ref.clone() },
                    }
                },
                "subscribe": {
                    "operationId": format!("subscribe_{name}"),
                    "message": {
                        "name": format!("{name}Publication"),
                        "payload": { "$ref": component_ref },
                    }
                }
            }),
        );
    }

    let doc = json!({
        "asyncapi": "2.6.0",
        "info": {
            "title": "Cherenkov realtime API",
            "version": "0.1.0",
            "description": "Generated by cherenkov-sdk-ts from a server config file.",
        },
        "servers": {
            "default": {
                "url": "ws://localhost:7000/connect/v1",
                "protocol": "ws",
            }
        },
        "channels": channels,
        "components": {
            "schemas": schemas,
        }
    });

    Ok(serde_yaml::to_string(&doc)?)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn renders_yaml_with_publish_and_subscribe_per_namespace() {
        let schema = serde_json::json!({
            "type": "object",
            "required": ["sku"],
            "properties": { "sku": { "type": "string" } }
        });
        let out = render(&[("orders".to_owned(), schema)]).unwrap();
        assert!(out.contains("asyncapi: 2.6.0"));
        assert!(out.contains("operationId: publish_orders"));
        assert!(out.contains("operationId: subscribe_orders"));
        assert!(out.contains("ordersPayload"));
    }
}
