//! TypeScript SDK code generator.
//!
//! Reads (namespace, JSON Schema) pairs and emits a single `.ts` file
//! containing one type per namespace plus a thin `CherenkovClient`
//! wrapper around the WebSocket protocol. The client is intentionally
//! transport-agnostic in shape — applications wire their own framing —
//! so the output stays a few hundred lines and is easy to audit.

use serde_json::Value;

const PRELUDE: &str = r#"// AUTO-GENERATED by cherenkov-sdk-ts. Do not edit by hand.
// Wire protocol: cherenkov.v1
// Each declared namespace has a typed publish helper; channels in
// undeclared namespaces accept arbitrary payloads.

export interface CherenkovTransport {
  send(bytes: Uint8Array): Promise<void>;
  onMessage(handler: (bytes: Uint8Array) => void): void;
}

export interface PublishOptions {
  requestId?: number;
}

export class CherenkovClient {
  private nextRequestId = 1;
  constructor(private readonly transport: CherenkovTransport) {}

  publish(channel: string, data: Uint8Array, opts: PublishOptions = {}): Promise<void> {
    // Encoding the v1 Publish frame is left to a wire library; this
    // SDK passes the channel + payload through to the transport.
    const requestId = opts.requestId ?? this.nextRequestId++;
    return this.transport.send(encodePublishFrame(requestId, channel, data));
  }
}

// Implemented in the runtime companion package.
declare function encodePublishFrame(
  requestId: number,
  channel: string,
  data: Uint8Array,
): Uint8Array;
"#;

/// Render the TypeScript module body for the given namespaces.
pub fn render(namespaces: &[(String, Value)]) -> String {
    let mut out = String::from(PRELUDE);
    out.push('\n');
    for (name, schema) in namespaces {
        out.push_str(&format!("\n// Namespace: {name}\n"));
        out.push_str(&format!(
            "export type {} = {};\n",
            type_name(name),
            ts_type(schema)
        ));
        out.push_str(&format!(
            "export function publish{}(client: CherenkovClient, channel: string, value: {}, encode: (v: {}) => Uint8Array): Promise<void> {{\n  return client.publish(channel, encode(value));\n}}\n",
            type_name(name),
            type_name(name),
            type_name(name),
        ));
    }
    out
}

fn type_name(namespace: &str) -> String {
    let mut out = String::new();
    let mut upper_next = true;
    for c in namespace.chars() {
        if c.is_alphanumeric() {
            if upper_next {
                out.extend(c.to_uppercase());
                upper_next = false;
            } else {
                out.push(c);
            }
        } else {
            upper_next = true;
        }
    }
    if out.is_empty() {
        "Payload".to_owned()
    } else {
        format!("{out}Payload")
    }
}

fn ts_type(schema: &Value) -> String {
    match schema.get("type").and_then(|v| v.as_str()) {
        Some("string") => "string".to_owned(),
        Some("integer") | Some("number") => "number".to_owned(),
        Some("boolean") => "boolean".to_owned(),
        Some("array") => {
            let item = schema
                .get("items")
                .map(ts_type)
                .unwrap_or_else(|| "unknown".to_owned());
            format!("{item}[]")
        }
        Some("object") => render_object(schema),
        _ => "unknown".to_owned(),
    }
}

fn render_object(schema: &Value) -> String {
    let required: std::collections::BTreeSet<&str> = schema
        .get("required")
        .and_then(|v| v.as_array())
        .map(|arr| arr.iter().filter_map(|v| v.as_str()).collect())
        .unwrap_or_default();
    let Some(props) = schema.get("properties").and_then(|v| v.as_object()) else {
        return "Record<string, unknown>".to_owned();
    };
    let mut out = String::from("{ ");
    let mut first = true;
    for (key, value) in props {
        if !first {
            out.push_str("; ");
        }
        first = false;
        let q = if required.contains(key.as_str()) {
            ""
        } else {
            "?"
        };
        out.push_str(&format!("{key}{q}: {}", ts_type(value)));
    }
    out.push_str(" }");
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn renders_object_namespace() {
        let schema = serde_json::json!({
            "type": "object",
            "required": ["sku"],
            "properties": {
                "sku": { "type": "string" },
                "qty": { "type": "integer" },
            }
        });
        let out = render(&[("orders".to_owned(), schema)]);
        assert!(out.contains("export type OrdersPayload = { qty?: number; sku: string }"));
        assert!(out.contains("publishOrdersPayload"));
    }

    #[test]
    fn type_name_strips_punctuation() {
        assert_eq!(type_name("rooms.lobby"), "RoomsLobbyPayload");
        assert_eq!(type_name("orders"), "OrdersPayload");
    }
}
